backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "/images"

locale: "ar"

collections:
  - label: "المنتجات"
    name: "products"
    files:
      - label: "قائمة المنتجات"
        name: "products_file"
        file: "products.json"
        format: "json"
        fields:
          - label: "المنتجات"
            name: "products"
            widget: "list"
            summary: "{{fields.name}} ({{fields.category}})"
            fields:
              - { label: "القسم", name: "category", widget: "select", options: ["الغذائية","المنظفات","الكوزمتك","المنزلية والمفروشات","العروض"] }
              - { label: "الاسم", name: "name", widget: "string" }
              - { label: "السعر بالدينار", name: "priceIQD", widget: "number", value_type: "int", min: 0, required: false }
              - { label: "الوصف", name: "desc", widget: "text", required: false }
              - { label: "صورة المنتج", name: "img", widget: "image" }
